name = "vite-plugin-ssr-vue-starter"
main = "wrangler/worker.mjs"
compatibility_date = "2022-05-03"

[site]
bucket = "dist/client"

[dev]
ip = "0.0.0.0"
port = 3000

[[kv_namespaces]]
id = "40537e421da14006af9b9949c46c7400"
preview_id = "1b7927754b3c4db990e1a2bc3e11605b"
binding = "DATA"
