name = "vite-plugin-ssr-vue-starter"
main = "wrangler/worker.mjs"
compatibility_date = "2022-05-03"

[site]
bucket = "dist/client"

[dev]
ip = "0.0.0.0"
port = 3000

[[kv_namespaces]]
id = "46a34081c7464164beaeb904316dc84d"
preview_id = "4bd590006f944d2a935b37c28856ec38"
binding = "DATA"
