compatibility_date = "2022-05-03"
vars = { MODE = "production" }
# name = "worker-sites-example"
# main = "wr_worker.js"
# site = { bucket = "./public" }

[[kv_namespaces]]
id = "40537e421da14006af9b9949c46c7400"
preview_id = "1b7927754b3c4db990e1a2bc3e11605b"
binding = "DATA"

[env.development]
vars = { MODE = "development" }

[[env.development.kv_namespaces]]
id = "40537e421da14006af9b9949c46c7400"
preview_id = "1b7927754b3c4db990e1a2bc3e11605b"
binding = "DATA"
