// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyExampleComponent: typeof import('./../components/ExampleComponent.vue')['default']
    MyExampleMarkdown: typeof import('./../components/ExampleMarkdown.md')['default']
    VectorLogo: typeof import('./../assets/vectors/logo.svg?component')['default']
  }
}
