/// <reference types="@cloudflare/workers-types"/>

interface RequestInit {
  preview?: true;
  refresh?: true;
}

interface WorkerRequest extends Request {
  origin: string;
  path: string;
  params: Record<string, string>;
  query: Record<string, string>;
  fetch: typeof fetch;
}

interface WorkerEnvironment {
  SECRET?: string;
  FUNCTIONS: KVNamespace;
  __STATIC_CONTENT: KVNamespace;
}

// Renamed for consistency and clarity.
type WorkerContext = ExecutionContext;
type WorkerProps = Record<string, any>;
type WorkerRoute = { path: string, query: Record<string, string> };
type WorkerFetch = typeof fetch;

// In Cloudflare Workers, this module points to a JSON manifest that
// maps asset paths to Workers KV keys generated by Workers Sites.
declare module "__STATIC_CONTENT_MANIFEST" {
  const manifest: string;
  export default manifest;
}
