name: Deploy to Cloudflare Workers
on: { push: { branches: [main] } }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Setup Node Environment
        uses: actions/setup-node@v3
        with: { node-version: 16.x, cache: npm }

      - name: 3. Build Vite Output
        run: npm run build:vite

      - name: 4. Build Worker Bundle
        run: npm run build:bundle

      - name: 5. Deploy Via Wrangler
        run: npm run deploy:wrangler
