name: CI/CD
on: { push: { branches: [main] } }

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}


jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    outputs: { exists: "${{ steps.check.outputs.flag }}" }
    steps:

      - id: check
        if: ${{ env.CLOUDFLARE_API_TOKEN != '' }}
        run: echo "::set-output name=flag::EXISTS"


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !needs.secrets.outputs.exists }}
    steps:

      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Setup Node Environment
        uses: actions/setup-node@v3
        with: { node-version: 16.x, cache: npm }

      - name: 3. Install Dependecies
        run: npm ci

      - name: 4. Build Vite Output
        run: npm run build:vite

      - name: 5. Build Worker Bundle
        run: npm run build:bundle

      - name: 6. Deploy Via Wrangler
        run: npm run deploy:wrangler
