name: CI/CD
on: { push: { branches: [main] } }

env:
  CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
  CLOUDFLARE_ACCOUNT_ID: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Setup Node Environment
        uses: actions/setup-node@v3
        with: { node-version: 16.x, cache: npm }

      - name: 3. Install Dependecies
        run: npm ci

      - name: 4. Build Vite Output
        run: npm run build:vite

      - name: 5. Build Worker Bundle
        run: npm run build:bundle

      - name: 6. Deploy Via Wrangler
        run: npm run deploy:wrangler
